version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Quitamos puertos directos para usar dominios de Dokploy
    volumes:
      - backend_data:/app/data
    environment:
      - DATABASE_URL=file:./data/dev.db
      - JWT_SECRET=allride-super-secret-key-2026
      - MAPBOX_SECRET_TOKEN=${MAPBOX_SECRET_TOKEN}
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_MAPBOX_PUBLIC_TOKEN=pk.eyJ1IjoiZGpiYjE2MDg4MyIsImEiOiJjbWl4ZnVocGMwM3k4M2xvOXkzMXY2eWxhIn0.yNlKzNWQ7gwTGSCq5jI6IA
        - VITE_API_URL=https://allride-api.2.24.81.205.sslip.io

    # El puerto 80 es interno, Dokploy lo mapea al dominio
    depends_on:
      - backend
    restart: always

volumes:
  backend_data:
